import { test, expect } from '@playwright/test';

/**
 * End-to-End Critical Path Test
 * Tests complete workflow: Login → Add Customer → Allocate Plot → Record Payment → Verify Receipt
 * This test simulates the real business workflow
 */

test.describe('Critical User Journey', () => {
  test('complete workflow: customer to payment', async ({ page }) => {
    const timestamp = Date.now();
    const customerName = `E2E Test Customer ${timestamp}`;
    const customerPhone = `080${timestamp.toString().slice(-8)}`;
    const customerEmail = `e2e${timestamp}@test.com`;

    // STEP 1: Login
    await page.goto('/');
    await page.getByLabel(/email/i).fill('admin@pinnaclegroups.ng');
    await page.getByLabel(/password/i).fill('Test@123');
    await page.getByRole('button', { name: /sign in/i }).click();
    await page.waitForURL('/dashboard');
    
    await expect(page.getByRole('heading', { name: /dashboard/i })).toBeVisible();
    
    // STEP 2: Add Customer
    await page.getByRole('link', { name: /customers/i }).click();
    await page.waitForURL('/dashboard/customers');
    
    await page.getByRole('button', { name: /add customer/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    
    await page.getByLabel(/full name/i).fill(customerName);
    await page.getByLabel(/phone/i).fill(customerPhone);
    await page.getByLabel(/email/i).fill(customerEmail);
    
    await page.getByRole('button', { name: /save/i }).click();
    
    // Verify customer created
    await expect(page.getByText(/customer created/i)).toBeVisible({ timeout: 5000 });
    
    // Search for the customer
    await page.getByPlaceholder(/search/i).fill(customerName);
    await page.waitForTimeout(500);
    
    await expect(page.getByText(customerName)).toBeVisible();
    
    // STEP 3: Create Allocation
    await page.getByRole('link', { name: /allocations/i }).click();
    await page.waitForURL('/dashboard/allocations');
    
    await page.getByRole('button', { name: /create allocation/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    
    // Select the customer we just created
    await page.getByLabel(/customer/i).click();
    await page.getByRole('option', { name: new RegExp(customerName, 'i') }).click();
    
    // Select first available plot
    await page.getByLabel(/plot/i).click();
    await page.getByRole('option').first().click();
    
    // Choose outright payment
    await page.getByLabel(/payment plan/i).selectOption('outright');
    
    await page.getByRole('button', { name: /create/i }).click();
    
    // Verify allocation created
    await expect(page.getByText(/allocation created/i)).toBeVisible({ timeout: 5000 });
    
    // STEP 4: Record Payment
    await page.getByRole('link', { name: /payments/i }).click();
    await page.waitForURL('/dashboard/payments');
    
    await page.getByRole('button', { name: /record payment/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    
    // Select the allocation we just created
    await page.getByLabel(/allocation/i).click();
    await page.getByRole('option', { name: new RegExp(customerName, 'i') }).click();
    
    // Enter payment details
    await page.getByLabel(/amount/i).fill('1000000');
    await page.getByLabel(/payment method/i).selectOption('bank_transfer');
    await page.getByLabel(/reference/i).fill(`E2E-REF-${timestamp}`);
    
    await page.getByRole('button', { name: /save|record/i }).click();
    
    // Verify payment recorded
    await expect(page.getByText(/payment recorded/i)).toBeVisible({ timeout: 5000 });
    
    // STEP 5: Verify Receipt Generated
    // The receipt should be automatically generated by the backend trigger
    // Check if we can view it
    await page.waitForTimeout(2000); // Wait for async receipt generation
    
    const receiptButton = page.getByRole('button', { name: /view receipt/i }).first();
    if (await receiptButton.isVisible()) {
      await receiptButton.click();
      await expect(page.getByText(/receipt/i)).toBeVisible();
    }
    
    // STEP 6: Verify Dashboard Stats Updated
    await page.getByRole('link', { name: /dashboard/i }).click();
    await page.waitForURL('/dashboard');
    
    // Dashboard should reflect the new data
    await expect(page.getByText(/total customers/i)).toBeVisible();
    await expect(page.getByText(/total revenue/i)).toBeVisible();
    
    // STEP 7: Check Reports
    await page.getByRole('link', { name: /reports/i }).click();
    await page.waitForURL('/dashboard/reports');
    
    await expect(page.getByRole('heading', { name: /reports/i })).toBeVisible();
    
    // Should see revenue data
    await expect(page.getByText(/revenue/i)).toBeVisible();
  });

  test('performance: dashboard loads within 2 seconds', async ({ page }) => {
    // Login
    await page.goto('/');
    await page.getByLabel(/email/i).fill('admin@pinnaclegroups.ng');
    await page.getByLabel(/password/i).fill('Test@123');
    await page.getByRole('button', { name: /sign in/i }).click();
    
    // Measure dashboard load time
    const startTime = Date.now();
    await page.waitForURL('/dashboard');
    await page.waitForLoadState('networkidle');
    const loadTime = Date.now() - startTime;
    
    // Should load within 2 seconds
    expect(loadTime).toBeLessThan(2000);
    
    // All key metrics should be visible
    await expect(page.getByText(/total customers/i)).toBeVisible();
    await expect(page.getByText(/available plots/i)).toBeVisible();
    await expect(page.getByText(/total revenue/i)).toBeVisible();
  });

  test('responsive: mobile navigation works correctly', async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    
    // Login
    await page.goto('/');
    await page.getByLabel(/email/i).fill('admin@pinnaclegroups.ng');
    await page.getByLabel(/password/i).fill('Test@123');
    await page.getByRole('button', { name: /sign in/i }).click();
    await page.waitForURL('/dashboard');
    
    // Mobile menu should be visible
    const menuButton = page.getByRole('button', { name: /menu/i });
    if (await menuButton.isVisible()) {
      await menuButton.click();
      
      // Navigation links should be visible
      await expect(page.getByRole('link', { name: /customers/i })).toBeVisible();
      await expect(page.getByRole('link', { name: /allocations/i })).toBeVisible();
    }
  });

  test('error handling: network failure gracefully handled', async ({ page, context }) => {
    // Login first
    await page.goto('/');
    await page.getByLabel(/email/i).fill('admin@pinnaclegroups.ng');
    await page.getByLabel(/password/i).fill('Test@123');
    await page.getByRole('button', { name: /sign in/i }).click();
    await page.waitForURL('/dashboard');
    
    // Simulate network failure
    await context.setOffline(true);
    
    // Try to navigate
    await page.getByRole('link', { name: /customers/i }).click();
    
    // Should show error message
    await expect(page.getByText(/error|failed|offline/i)).toBeVisible({ timeout: 5000 });
    
    // Restore network
    await context.setOffline(false);
  });
});
